### ISSUE TITLE
could you provide load_data function json file

### ISSUE THREAD

**Issue by Akirataiki1989** [YongWookHa/craft-text-detector#1]
1. my data train & val folder tree like this (use icdar2015 train datasets):
./data/training/
  └─ img_1.jpg
  └─ img_1.json
  └─ img_4.jpg
  └─ img_4.json
             .
             .
./data/val/
  └─ img_2.jpg
  └─ img_2.json
  └─ img_3.jpg
  └─ img_3.json
             .
             .
2. each json file content：
{"image": {"file_name": "img_1.jpg"},
	         "text": {"word": [
			          {"value": "Genaxis Theatre","charbox": [["377","117"],["463","117"],["465","130"],["378","130"]]},
                                  {"value": "62-03","charbox": [["377","117"],["463","117"],["465","130"],["378","130"]]}]}}

3. def load_data(self, json_fn: Path)------>my write:
        with json_fn.open('r', encoding='utf8') as f:
                  data = json.load(f)
        image_fn = Path("{}".format(self.data_dir))
        image_fn = list(image_fn.glob("**/{}".format(data["image"]["file_name"])))
        if not image_fn:
            print("FileNotFoundError: image_fn : {}".format(image_fn))
            raise FileNotFoundError
        image = load_image(image_fn[0])
        char_boxes, words = [], []
              for word_d in data["text"]["word"]:
                 text = word_d["value"]
                 char_boxes.append(word_d["charbox"])
                 words.append(text)
       return image, np.array(char_boxes), words, image_fn[0]

4. Run preprocess.py i get: TypeError: __init__() missing 1 required positional argument: 'dtypes'

5. could you provide load_data function example json file,i need check where is wrong.thx

**Comment by YongWookHa** [comment]
Hi @Akirataiki1989.

https://github.com/YongWookHa/craft-text-detector/blob/7e30c956f9ce67a5f6c10cef33e1d0c8d233b6ae/datasets/craft_dataset.py#L13

`CustomDataset` class has sample `load_data` function.

Here's a json file I used with Custom Dataset. You might be able to find out with this.

```json
{
    "info": {
        "name": "Korean OCR Data Set",
        "description": "Korean OCR Data Set (print)",
        "date_created": "2021-03-09 13:00:16"
    },
    "image": {
        "file_name": "00110011041.jpg",
        "width": 2480,
        "height": 3508,
        "dpi": 300,
        "bit": 24
    },
    "license": {
        "output": "print",
        "font": "안동까투리체",
        "font_no": "01",
        "font_license": "안동시-무료글꼴",
        "font_url": "https://www.andong.go.kr/",
        "writer_no": "",
        "writer_gender": "",
        "writer_age": ""
    },
    "text": {
        "word": [
            {
                "wordbox": [
                    557,
                    251,
                    592,
                    312
                ],
                "value": "■",
                "source": "form",
                "letter": [
                    {
                        "charbox": [
                            559,
                            253,
                            590,
                            310
                        ],
                        "value": "■"
                    }
                ]
            },
            {
                "wordbox": [
                    284,
                    252,
                    416,
                    310
                ],
                "value": "【서식",
                "source": "form",
                "letter": [
                    {
                        "charbox": [
                            286,
                            254,
                            308,
                            309
                        ],
                        "value": "【"
                    },
                    {
                        "charbox": [
                            309,
                            254,
                            359,
                            308
                        ],
                        "value": "서"
                    },
                    {
                        "charbox": [
                            363,
                            254,
                            413,
                            308
                        ],
                        "value": "식"
                    }
                ]
            },
...

```

Have a good day.

**Comment by Akirataiki1989** [comment]
Thank you for responding so quickly,have a blessed day.

**Comment by YongWookHa** [comment]
Okay.

Close the issue when it's handled.
And please click ⭐ button if you can.

Thanks
